---
docker:
  buildkit: true
  image: tekki/perl

git:
  repo: https://github.com/Tekki/docker-perl-test
  version: '0.11'

global:
  app_folder: /usr/src/app
  description: 'Perl test images.'
  license: Artistic-2.0
  perl_db_modules:
    - DBI
    - DBD::mysql
    - DBD::MariaDB
    - DBD::Pg
    - DBD::SQLite
    - SQL::Abstract
  perl_modules:
    - Test::CPAN::Changes
    - Test::Deep
    - Test::Exception
    - Test::Output
    - Test::Pod
    - Test::Pod::Coverage
    - Test::Warn
  title: Perl-Test

releases:
  p32:
    from: perl:5.32
    versions:
      base:
        - 32-test
        - test
      db:
        - 32-dbtest
        - dbtest
      mojo:
        - 32-mojotest
        - mojotest
    perl_mojo_modules:
      - Mojolicious
  p30:
    from: perl:5.30
    versions:
      base:
        - 30-test
      db:
        - 30-dbtest
      mojo:
        - 30-mojotest
    perl_mojo_modules:
      - Mojolicious
  p28:
    from: perl:5.28
    versions:
      base:
        - 28-test
      db:
        - 28-dbtest
      mojo:
        - 28-mojotest
    perl_mojo_modules:
      - Mojolicious
  p26:
    from: perl:5.26
    versions:
      base:
        - 26-test
      db:
        - 26-dbtest
      mojo:
        - 26-mojotest
    perl_mojo_modules:
      - Mojolicious
  p24:
    from: perl:5.24
    versions:
      base:
        - 24-test
      db:
        - 24-dbtest
      mojo:
        - 24-mojotest
    perl_mojo_modules:
      - Mojolicious
  p22:
    from: perl:5.22
    versions:
      base:
        - 22-test
      db:
        - 22-dbtest
      mojo:
        - 22-mojotest
    perl_mojo_modules:
      - Mojolicious
  p20:
    from: perl:5.20
    versions:
      base:
        - 20-test
      db:
        - 20-dbtest
      mojo:
        - 20-mojotest
    perl_mojo_modules:
      - Mojolicious
  p16:
    from: perl:5.16
    versions:
      base:
        - 16-test
      db:
        - 16-dbtest
      mojo:
        - 16-mojotest
    perl_mojo_modules:
      - Mojolicious
  p10:
    from: perl:5.10
    versions:
      base:
        - 10-test
      db:
        - 10-dbtest
      mojo:
        - 10-mojotest
    perl_mojo_modules:
      - Mojolicious@8.43

templates:
  - source: docker-entrypoint.ep
    target: docker-entrypoint.sh
  - source: dockerfile.ep
    target: Dockerfile
